# Generated by Django 5.1.3 on 2024-11-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="posts",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.category",
            ),
            preserve_default=False,
        ),
    ]
